print("Please enter four numbers")
a = float(input("Number 1 = "))
b = float(input("Number 2 = "))
c = float(input("Number 3 = "))
d = float(input("Number 4 = "))
res = (a + b) / (c + d)
print("The result is %.2f" % (res))